### ISSUE TITLE
Milestone: get Racket-side map fully working

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#10]
Fully working means:

 * [x] satisfies contract `acc-array? -> acc-array?`
 * [x] this means `acc-array?` must be a union type that includes `acc-manifest-array` and `acc-deferred-computation`.
 * [x] the `map` function must be a wrapper that dispatches to `List.map` or `acc-map` appropriately.

**Comment by rrnewton** [comment]
Great, btw, it is nice to close these issues with a commit.  Just write "Closes #X" or "Fixes #X" in the commit message and it happens automatically.
