### ISSUE TITLE
v0.4 release checklist -- enter types!

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/accelerack#51]
* [x] equal? support
 * [v0.5] inter-module define-acc works (or can put this off one more release if needed)
 * [x] Handle (enforce) numeric type.  This can probably happen just in unify.
 * [x] Add until / until-array 
 * [x] Allow type-annotated function params in `(define (f x) ...)` form.
 * [x] Allow top-level `(: v ty)` signatures for functions.
 * [x] Add `sexp->acc-array` inverse of the existing function.
 * [x] Add `type-of` or some other way to view/debug types
 * [x] Finish `gentle-unify-arrows` to better localize function argument errors
 * [x] Fix typechecking for procedure application
 * [x] Add rudimentary `define-acc` (manifest) scalar support
 * [x] add free-vars for envs and handle generalize correctly

**Comment by rrnewton** [comment]
Just updated this with several more small things to remember to do.

**Comment by rrnewton** [comment]
Oops, we need to buff up the prim list also, for scalar functions.
